# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbden_tutorial',
                'doc_host': 'https://akxs14.github.io',
                'git_url': 'https://github.com/akxs14/nbden_tutorial',
                'lib_path': 'nbden_tutorial'},
  'syms': {'nbden_tutorial.core': {'nbden_tutorial.core.foo': ('core.html#foo', 'nbden_tutorial/core.py')}}}
